apt-get update
apt-get install -y python-dev
apt-get install -y cmake
apt-get install -y git
apt-get install -y gfortran
apt-get install -y screen
apt-get install -y zip
apt-get install -y vim
apt-get install -y libprotobuf-dev
apt-get install -y protobuf-compiler
apt-get install -y libleveldb-dev
apt-get install -y libsnappy-dev
apt-get install -y libhdf5-serial-dev
apt-get install -y libopencv-dev
apt-get install -y libboost-all-dev
apt-get install -y libopenblas-dev
apt-get install -y liblmdb-dev
apt-get install -y libgoogle-glog-dev
apt-get install -y libgflags-dev
apt-get install -y python-pip
apt-get install -y python-virtualenv
apt-get install -y python-numpy
apt-get install -y python-scipy
apt-get install -y python-opencv
apt-get install -y python-boto
apt-get install -y python-skimage
apt-get install -y python-protobuf
apt-get install -y ipython
